### ISSUE TITLE
Add Serde support

### ISSUE THREAD

**Issue by dtolnay** [Wallacoloo/jagged_array#1]
I would love to use these as long as I can serialize and deserialize them!

**Comment by Wallacoloo** [comment]
Just released v0.2.1 which adds support for this. Under the hood, deserialization is done by deserializing into `Vec<Vec<T>>` and then constructing a `Jagged2` type, so it's not at all efficient. Serialization doesn't do any needless allocations though.

Someday (tm) I'll take a stab at improving the deserialization code, but I'd need to study Serde further first.

**Comment by Wallacoloo** [comment]
FWIW the freshly published v0.2.2 fixes efficiency issues with the deserialization method. It now deserializes directly into a contiguous block of memory rather than through a `Vec<Vec<T>>`.
